services:
  - type: web
    name: multi-tasker-streamlit
    runtime: python
    plan: free

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt --timeout 120 --retries 5

    startCommand: |
      streamlit run main.py --server.port $PORT --server.address 0.0.0.0
